import Achievement from '../resources/achievement';
import ActivityType from '../resources/activity-type';
import Aggregate from '../resources/aggregate';
import AlldayActivity from '../resources/allday-activity';
import Bodymass from '../resources/bodymass';
import Course from '../resources/course';
import DataSource from '../resources/data-source';
import DataSourcePriority from '../resources/data-source-priority';
import Gear from '../resources/gear';
import Group from '../resources/group';
import GroupInvite from '../resources/group-invite';
import GroupLeaderboard from '../resources/group-leaderboard';
import GroupPurpose from '../resources/group-purpose';
import GroupUser from '../resources/group-user';
import HeartRateZones from '../resources/heart-rate-zones';
import HeartRateZoneCalculation from '../resources/heart-rate-zone-calculation';
import MapMarkerImage from '../resources/map-marker-image';
import Membership from '../resources/membership';
import OverallLeaderboardEntry from '../resources/overall-leaderboard-entry';
import Page from '../resources/page';
import Privacy from '../resources/privacy';
import Remoteconnection from '../resources/remoteconnection';
import Remoteconnectiontype from '../resources/remoteconnectiontype';
import Route from '../resources/route';
import RouteBookmark from '../resources/route-bookmark';
import Sleep from '../resources/sleep';
import User from '../resources/user'
import UserAchievement from '../resources/user-achievement';
import Usergear from '../resources/usergear';
import UserProfilePhoto from '../resources/user-profile-photo';
import UserRole from '../resources/user-role';
import UserStats from '../resources/user-stats';
import Webhook from '../resources/webhook';
import Workout from '../resources/workout';
import WorkoutHeartRate from '../resources/workout-heart-rate';

const API_VERSION = 'v7.1';

export default {
  achievement: new Achievement(API_VERSION, 'achievement'),
  activityType: new ActivityType(API_VERSION, 'activity_type'),
  aggregate: new Aggregate(API_VERSION, 'aggregate'),
  alldayActivity: new AlldayActivity(API_VERSION, 'allday_activity'),
  bodymass: new Bodymass(API_VERSION, 'bodymass'),
  course: new Course(API_VERSION, 'course'),
  dataSource: new DataSource(API_VERSION, 'data_source'),
  dataSourcePriority: new DataSourcePriority(API_VERSION, 'data_source_priority'),
  gear: new Gear(API_VERSION, 'gear'),
  group: new Group(API_VERSION, 'group'),
  groupInvite: new GroupInvite(API_VERSION, 'group_invite'),
  groupLeaderboard: new GroupLeaderboard(API_VERSION, 'group_leaderboard'),
  groupPurpose: new GroupPurpose(API_VERSION, 'group_purpose'),
  groupUser: new GroupUser(API_VERSION, 'group_user'),
  heartRateZones: new HeartRateZones(API_VERSION, 'heart_rate_zones'),
  heartRateZoneCalculation: new HeartRateZoneCalculation(API_VERSION, 'heart_rate_zone_calculation'),
  mapMarkerImage: new MapMarkerImage(API_VERSION, 'map_marker_image'),
  membership: new Membership(API_VERSION, 'membership'),
  overallLeaderboardEntry: new OverallLeaderboardEntry(API_VERSION, 'overall_leaderboard_entry'),
  page: new Page(API_VERSION, 'page'),
  privacy: new Privacy(API_VERSION, 'privacy_option'),
  remoteconnection: new Remoteconnection(API_VERSION, 'remoteconnection'),
  remoteconnectiontype: new Remoteconnectiontype(API_VERSION, 'remoteconnectiontype'),
  route: new Route(API_VERSION, 'route'),
  routeBookmark: new RouteBookmark(API_VERSION, 'route_bookmark'),
  sleep: new Sleep(API_VERSION, 'sleep'),
  user: new User(API_VERSION, 'user'),
  userAchievement: new UserAchievement(API_VERSION, 'user_achievement'),
  usergear: new Usergear(API_VERSION, 'usergear'),
  userProfilePhoto: new UserProfilePhoto(API_VERSION, 'user_profile_photo'),
  userRole: new UserRole(API_VERSION, 'user_role'),
  userStats: new UserStats(API_VERSION, 'user_stats'),
  webhook: new Webhook(API_VERSION, 'webhook'),
  workout: new Workout(API_VERSION, 'workout'),
  workoutHeartRate: new WorkoutHeartRate(API_VERSION, 'workout_heart_rate')
}
